import logging
from typing import Any

from google.adk.workflow import node
from google.adk.agents.context import Context
from google.adk.agents.llm_agent import LlmAgent
from google.adk.agents.llm_agent_config import LlmAgentConfig

logger = logging.getLogger("fable.lore_keeper")

def create_lore_keeper() -> LlmAgent:
    keeper_config = LlmAgentConfig(
        name="lore_keeper",
        description="Fuses raw text and wiki research into the FableAgentState.",
        model="gemini-3.1-flash-lite-preview",
        instruction="""
        You are the Lore Keeper.
        You will receive a massive array of research generated by the Lore Hunter Swarm.
        
        Your job is to synthesize this research into structured formats for the Fable Engine.
        You must output JSON matching the required schema to populate the World Bible.
        
        Focus heavily on:
        1. "forbidden_concepts": Secrets and spoilers the protagonist MUST NOT know.
        2. "anti_worf_rules": Baseline competence rules for major characters.
        
        You will be provided with tools to update these dictionaries.
        """
    )
    
    agent = LlmAgent.from_config(keeper_config, config_abs_path="")
    
    # In a full implementation, we attach specific tools here (e.g., `update_world_bible`)
    # that allow the agent to write its synthesis back into `ctx.state`.
    # For now, we rely on the agent to output the synthesis for the next node.
    
    return agent
    
# ---------------------------------------------------------------------------
# State Injection Node
# ---------------------------------------------------------------------------

from google.adk.events.event import Event
from google.adk.events.request_input import RequestInput
from google.adk.events.event_actions import EventActions
from typing import AsyncGenerator

@node(name="lore_keeper_injector")
async def inject_lore_to_state(ctx: Context, node_input: Any) -> AsyncGenerator[Any, None]:
    """
    Takes the output from the Lore Keeper LLM, dumps it into the state,
    and suspends the graph to allow the user to review the Primer.
    """
    primer_text = "World Primer Synthesis Failed."
    
    if hasattr(node_input, "content") and node_input.content and node_input.content.parts:
        primer_text = node_input.content.parts[0].text
        ctx.state["crossover_primer"] = primer_text
        logger.info("Successfully injected Crossover Primer into State.")
        
    # Check if we are resuming from the review
    interrupt_id = "setup_world_primer"
    resume_payload = ctx.resume_inputs.get(interrupt_id)
    
    if not resume_payload:
        # Suspend and ask user to review
        yield RequestInput(
            interrupt_id=interrupt_id,
            message=primer_text
        )
        return
        
    # User approved, continue the graph
    logger.info("User approved World Primer. Transitioning to Storyteller.")
    
    yield Event()