import logging
from typing import Any, AsyncGenerator, List, Dict

from pydantic import BaseModel, Field

from google.adk.workflow import node
from google.adk.agents.context import Context
from google.adk.agents.llm_agent import LlmAgent
from google.adk.agents.llm_agent_config import LlmAgentConfig
from google.adk.events import Event, EventActions, RequestInput
from google.genai import types

logger = logging.getLogger("fable.lore_keeper")


def create_lore_keeper() -> LlmAgent:
    keeper_config = LlmAgentConfig(
        name="lore_keeper",
        description="Fuses raw text and wiki research into the FableAgentState.",
        model="gemini-3.1-flash-lite-preview",
        instruction="""
        You are the Lore Keeper.
        You will receive a massive array of research generated by the Lore Hunter Swarm.

        Your job is to synthesize this research into structured formats for the Fable Engine.
        You must output JSON matching the required schema to populate the World Bible.

        Focus heavily on:
        1. "forbidden_concepts": Secrets and spoilers the protagonist MUST NOT know.
        2. "anti_worf_rules": Baseline competence rules for major characters.

        You will be provided with tools to update these dictionaries.
        """
    )

    agent = LlmAgent.from_config(keeper_config, config_abs_path="")
    return agent


# ---------------------------------------------------------------------------
# Fallback Extractor
# ---------------------------------------------------------------------------

class WorldBibleExtraction(BaseModel):
    forbidden_concepts: List[str] = Field(default_factory=list, description="Secrets and spoilers the protagonist MUST NOT know.")
    anti_worf_rules: Dict[str, str] = Field(default_factory=dict, description="Baseline competence rules for major characters.")


def create_fallback_extractor() -> LlmAgent:
    agent = LlmAgent(
        name="fallback_extractor",
        description="Explicitly extracts World Bible data from raw text when the primary agent fails.",
        model="gemini-3.1-flash-lite-preview",
        instruction="Extract the forbidden concepts and anti-worf rules from the provided text into structured JSON.",
        output_schema=WorldBibleExtraction,
        generate_content_config=types.GenerateContentConfig(response_mime_type="application/json")
    )
    return agent


@node(name="fallback_injector", rerun_on_resume=True)
async def fallback_injector(ctx: Context, node_input: Any) -> AsyncGenerator[Any, None]:
    """Injects the explicitly extracted JSON into the state."""
    logger.info("Applying fallback extraction...")
    if hasattr(node_input, "output") and isinstance(node_input.output, WorldBibleExtraction):
        ctx.state["forbidden_concepts"] = node_input.output.forbidden_concepts
        ctx.state["anti_worf_rules"] = node_input.output.anti_worf_rules
        logger.info("Successfully populated state via fallback extractor.")

    # `temp:` prefix bypasses state_schema validation (sessions/state.py:39-40);
    # crossover_primer is internal scratch state, not declared in FableAgentState.
    primer_text = ctx.state.get("temp:crossover_primer", "World Primer Synthesis Complete (Fallback).")
    interrupt_id = "setup_world_primer"
    resume_payload = ctx.resume_inputs.get(interrupt_id)

    if not resume_payload:
        yield RequestInput(
            interrupt_id=interrupt_id,
            message=primer_text
        )
        return

    logger.info("User approved World Primer (Fallback path). Transitioning to Intent Router.")
    yield Event(actions=EventActions(route="success"))


# ---------------------------------------------------------------------------
# State Injection Node
# ---------------------------------------------------------------------------

@node(name="lore_keeper_injector", rerun_on_resume=True)
async def inject_lore_to_state(ctx: Context, node_input: Any) -> AsyncGenerator[Any, None]:
    """
    Takes the output from the Lore Keeper LLM, dumps it into the state,
    and suspends the graph to allow the user to review the Primer.
    """
    primer_text = "World Primer Synthesis Failed."

    if hasattr(node_input, "content") and node_input.content and node_input.content.parts:
        primer_text = node_input.content.parts[0].text
        # `temp:` prefix bypasses state_schema validation (sessions/state.py:39-40).
        ctx.state["temp:crossover_primer"] = primer_text
        logger.info("Successfully injected Crossover Primer into State.")

    # Programmatic Fallback Extraction.
    # Check if tools mutated the state via the public to_dict() snapshot.
    state_snapshot = ctx.state.to_dict()
    has_forbidden = "forbidden_concepts" in state_snapshot
    has_anti_worf = "anti_worf_rules" in state_snapshot

    if not has_forbidden and not has_anti_worf:
        logger.warning("Lore Keeper failed to mutate state (hallucination). Routing to fallback extractor.")
        # Store the research dump / primer text so the fallback extractor can process it
        yield Event(actions=EventActions(route="fallback"))
        return

    # Check if we are resuming from the review
    interrupt_id = "setup_world_primer"
    resume_payload = ctx.resume_inputs.get(interrupt_id)

    if not resume_payload:
        # Suspend and ask user to review
        yield RequestInput(
            interrupt_id=interrupt_id,
            message=primer_text
        )
        return

    # User approved, continue the graph
    logger.info("User approved World Primer. Transitioning to Intent Router.")

    yield Event(actions=EventActions(route="success"))
